### ISSUE TITLE
syntax error please help

### ISSUE THREAD

**Issue by frankiehathaway** [4n4nk3/Wordlister#13]
File "wordlister.py", line 14
    def init_argparse() -> argparse.ArgumentParser:
                        ^
SyntaxError: invalid syntax

**Comment by 4n4nk3** [comment]
Good morning.
Can you please verify which version of python are you running?
Wordlister is written in python 3.8.
The error you get suggests me that you are probably running an old version of python itself that doesn't support the same syntax. Using correct version should solve your problem.

**Comment by frankiehathaway** [comment]
thanks a lot it worked. my bad.
