### ISSUE TITLE
Combination not working as expected

### ISSUE THREAD

**Issue by Soussef24** [4n4nk3/Wordlister#18]
Hello,

I got this version of the script (https://raw.githubusercontent.com/4n4nk3/Wordlister/master/wordlister.py) and it doesn't seem to work as expected, maybe after the partial rewrite.

It only combines the same words and only if they have a difference in the case of one of their letters, and it ignores all the other words. the perm option is also not taken a max value for permutations but as fixed values, if "--perm 3" it only does permutations of 3 words and skip 1 and 2.

I'm attaching my input and output files for this command : 
"python3 ./wordlister.py --input test_words.txt --output test_passwords.txt --perm 2 --min 0 --max 150"
[test_passwords.txt](https://github.com/4n4nk3/Wordlister/files/10870729/test_passwords.txt)
[test_words.txt](https://github.com/4n4nk3/Wordlister/files/10870730/test_words.txt)

Thanks.

**Comment by 4n4nk3** [comment]
Hello Soussef24, thank you for your report!
The PR from @Razi96 should have addressed the issue 👍🏻
Please try the new version
