### ISSUE TITLE
how can i make a 8 long wordlist with 7-6  digits and at least 1 or 2 Capital alphabet character? 

### ISSUE THREAD

**Issue by minanagehsalalma** [4n4nk3/Wordlister#9]
Just like this 12H45678 or 1D3456P8
and how big would it be ? 
@4n4nk3

**Comment by 4n4nk3** [comment]
This software generate wordlists mangling existing wordlists togheter.
To do what you want to do you need a different software, something like Crunch wordlist generator that can generate them completely randomly based on selected rules.

**Comment by minanagehsalalma** [comment]
> This software generate wordlists mangling existing wordlists togheter.
> To do what you want to do you need a different software, something like Crunch wordlist generator that can generate them completely randomly based on selected rules.

@4n4nk3 hmm. Thanks but I don't think crunch have the required rules and doing it manually using the - t  @@@@HG@@  would take a lot of time .

**Comment by 4n4nk3** [comment]
You can also have a look at "hashcat" mask attack.

**Comment by minanagehsalalma** [comment]
> You can also have a look at "hashcat" mask attack.

Yup i did and i think i will do it again .

**Comment by dydfrancis** [comment]
please i really need help on this tool may be video tutorial thanks
